services:
  # Frontend Service
  - type: web
    name: verbia-bookstore-frontend # You can change this to your unique name
    runtime: static
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_URL
        value: https://verbia-bookstore-backend.onrender.com # This should match your backend service name

  # Backend Service
  - type: web
    name: verbia-bookstore-backend # You can change this to your unique name
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: "npm install && npm run db:migrate"
    startCommand: "node src/server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: verbia-bookstore-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - fromGroup: verbia-bookstore-secrets # You will create this group in Render

databases:
  # PostgreSQL Database
  - name: verbia-bookstore-db # You can change this to your unique name
    plan: free

envVarGroups:
  - name: verbia-bookstore-secrets
    envVars:
      - key: JWT_SECRET
        value: 9888bcb02f9e924a9c38a67d5296689b20727d58d74cfc10a48eaf775eb77f050084631dfcca18849c863801494f7f6c5e4fcf26bb8e
      - key: SESSION_SECRET
        value: YOUR_SESSION_SECRET # Replace with a long random string
      - key: STRIPE_SECRET_KEY
        value: YOUR_STRIPE_SECRET_KEY # Replace with your Stripe Secret Key
      - key: CLIENT_URL
        value: https://verbia-bookstore-frontend.onrender.com # This should match your frontend service name
